pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    DemoImgThumbnail:
                        items:
                            -
                                method: scaleByWidth
                                arguments:
                                    width: 400
                                    forceResize: false
                        medias: {  }
                        name: DemoImgThumbnail
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1657518103
                        creationDate: 1657518028
                        preserveAnimation: false
